\documentclass{article}

\usepackage{amsmath}
\usepackage{amscd}
\usepackage[tableposition=top]{caption}
\usepackage{ifthen}
\usepackage[utf8]{inputenc}

\begin{document}

\title{mmod Demo}
\author{David Winter}
\maketitle

This is a short demo of \verb@mmod@ command in R. 
As an example, we are going to examine the \verb@nancycats@ data that comes
with \verb@adegenet@. This dataset contains microsattelite genotypes
taken from feral cats in Nancy, France. Our goal is to see (a) to what degree
sub-populations of these cats are differentiated from each other and (b) if that
differentiation can be explained by the geographic distance between subpopulations. 
So let's start. 

<<start>>=
library(mmod)
data(nancycats)
nancycats
@

The nancycats data is provided by \verb@adegenet@ and comes in that library's
default \verb@genind@ class. The functions in \verb@mmod@ work on genind objects, 
so you would usually start by reading in your data using \verb@read.genepop()@ 
 
Now that we have our data on hand, we want to know how strong any divergence 
between sub-populations might be. We can look a bunch off different statistics
using a single command:

<<diffstat>>=
diff_stats(nancycats)
@


OK, so what's all that then? The first table has statistics calculated individually 
for each locus in the dataset. \verb@Hs@ and \verb@Hs@ are estimates of the 
heterozgosity expected for this population with and without the sub-populations
defined in the nancycats data. We need to use those to calculate the measures of 
population divergence so we might as well display them at the same time. 
\verb@Gst@ is the standard (Nei) Gst, GPrimest is Hedricks \verb@G'st@ and D 
 is Josts' \verb@D@.
\par D is the easiest statistic to interperate, as you expect to find D=0 for
populations with no differentiation and D=1 for completely differentiated 
populations. As you can see, different loci give quite different estimates of
divergence but they range from ~0.1 - 0.4. I'd say that's reasonably 
substantial. You might also want to see how regular old \verb@Gst@ stacks up
with \verb@D@
<<label=fig1plot>>=
nc.diff_stats <- diff_stats(nancycats)
with(nc.diff_stats, plot(per.locus[,"Gst"], per.locus[,"D"]))
fit <- with(nc.diff_stats, (lm(per.locus[,"D"] ~ per.locus[,"Gst"])))
abline(fit)
@
\begin{figure}
\begin{center}
<<label=fig1, fig=TRUE, echo=FALSE>>=
<<fig1plot>>
@
\end{center}
\label{Gst v D}
\caption{Nei's Gst against Jost's D}
\end{figure}

\par The second part of the list returned by \verb@diff_stat@ contains global
estimates of each of these statistics. For Gst and G'st these are based on the 
average of Hs and Ht across loci. For D you get two, the harmonic mean of the
estimate of D for locus and, because that method won't work if you end up with
negative estimates of D, one calculated as per Gst and G'st. The global 
estimates seem to be pointing toward substantial differentiation for these
populations. 

\par Next, we want to know if geography can explain that differentiation. 
The nancycats data comes with coordinates for each populations. We can use
these to get Euclidean distances

<<label=show_coords>>=
head(nancycats@other$xy, 4)
nc.pop_dists <- dist(nancycats@other$xy, method="euclidean")
@

\par \verb@mmod@ provides functions to calculate pairwise versions of each of
the differntiation statistics. Because we want to perform a Mantel test, we'll
use the "linearized" version of each stat, which is just x/(1-x).

<<label=pw>>=
nc.pw_D <- pairwise_D(nancycats, linearized=TRUE)
nc.pw_Gst <- pairwise_Gst_Nei(nancycats, linearized=TRUE)
@

\par The libary \verb@ade4@, which is loaded with \verb@mmod@ provides 
functions to perform Mantel tests on distance matrices. 

<<label=mantel>>=
mantel.rtest(nc.pw_D, log(nc.pop_dists), 999)
mantel.rtest(nc.pw_Gst, log(nc.pop_dists), 999)
@
\par So, the geographic distance between these populations can't explain the 
genetic divergences we see: the correlation is small and non-significant. 
If you like, we can also visualize this relationship for each statistic

<<label=fig2plot>>=
par(mfrow=c(2,1))
fit <- lm(as.vector(nc.pw_D) ~ as.vector(nc.pop_dists))
plot(as.vector(nc.pw_D) ~ as.vector(nc.pop_dists))
abline(fit)
fit <- lm(as.vector(nc.pw_Gst) ~ as.vector(nc.pop_dists))
plot(as.vector(nc.pw_Gst) ~ as.vector(nc.pop_dists))
abline(fit)
@
\begin{figure}
\begin{center}
<<label=fig2, fig=TRUE, echo=FALSE>>=
<<fig2plot>>
@
\end{center}
\label{Gst v D}
\caption{Geographic distance doesn't explain genetic differentiation}
\end{figure}


\end{document}

